#!/usr/bin/env bash
# 把本次归档全部移回原位（在仓库根目录运行）
set -e
cd "$(dirname "$0")/../.."
mkdir -p "$(dirname "results_bcppo_A")"; git mv "_archive/2026-10-02/results_bcppo_A" "results_bcppo_A"
mkdir -p "$(dirname "results_bcppo_A_rem")"; git mv "_archive/2026-10-02/results_bcppo_A_rem" "results_bcppo_A_rem"
mkdir -p "$(dirname "results_bcppo_B")"; git mv "_archive/2026-10-02/results_bcppo_B" "results_bcppo_B"
mkdir -p "$(dirname "results_cfcredit")"; git mv "_archive/2026-10-02/results_cfcredit" "results_cfcredit"
mkdir -p "$(dirname "results_cfcredit_n1")"; git mv "_archive/2026-10-02/results_cfcredit_n1" "results_cfcredit_n1"
mkdir -p "$(dirname "results_cfcredit_n2")"; git mv "_archive/2026-10-02/results_cfcredit_n2" "results_cfcredit_n2"
mkdir -p "$(dirname "results_cfcredit_n3")"; git mv "_archive/2026-10-02/results_cfcredit_n3" "results_cfcredit_n3"
mkdir -p "$(dirname "results_cfcredit_n6")"; git mv "_archive/2026-10-02/results_cfcredit_n6" "results_cfcredit_n6"
mkdir -p "$(dirname "results_cfcredit_real")"; git mv "_archive/2026-10-02/results_cfcredit_real" "results_cfcredit_real"
mkdir -p "$(dirname "results_curve")"; git mv "_archive/2026-10-02/results_curve" "results_curve"
mkdir -p "$(dirname "results_fqi_L4")"; git mv "_archive/2026-10-02/results_fqi_L4" "results_fqi_L4"
mkdir -p "$(dirname "results_g5_anticip")"; git mv "_archive/2026-10-02/results_g5_anticip" "results_g5_anticip"
mkdir -p "$(dirname "results_g5_fs")"; git mv "_archive/2026-10-02/results_g5_fs" "results_g5_fs"
mkdir -p "$(dirname "results_g5_gae")"; git mv "_archive/2026-10-02/results_g5_gae" "results_g5_gae"
mkdir -p "$(dirname "results_g5_mc")"; git mv "_archive/2026-10-02/results_g5_mc" "results_g5_mc"
mkdir -p "$(dirname "results_g5b_anticip")"; git mv "_archive/2026-10-02/results_g5b_anticip" "results_g5b_anticip"
mkdir -p "$(dirname "results_g5b_fs")"; git mv "_archive/2026-10-02/results_g5b_fs" "results_g5b_fs"
mkdir -p "$(dirname "results_g5b_gae")"; git mv "_archive/2026-10-02/results_g5b_gae" "results_g5b_gae"
mkdir -p "$(dirname "results_g5b_mc")"; git mv "_archive/2026-10-02/results_g5b_mc" "results_g5b_mc"
mkdir -p "$(dirname "results_gate")"; git mv "_archive/2026-10-02/results_gate" "results_gate"
mkdir -p "$(dirname "results_gm_bc_s0")"; git mv "_archive/2026-10-02/results_gm_bc_s0" "results_gm_bc_s0"
mkdir -p "$(dirname "results_gm_bc_s1")"; git mv "_archive/2026-10-02/results_gm_bc_s1" "results_gm_bc_s1"
mkdir -p "$(dirname "results_gm_bc_s2")"; git mv "_archive/2026-10-02/results_gm_bc_s2" "results_gm_bc_s2"
mkdir -p "$(dirname "results_gm_bconly_s0")"; git mv "_archive/2026-10-02/results_gm_bconly_s0" "results_gm_bconly_s0"
mkdir -p "$(dirname "results_gm_bconly_s1")"; git mv "_archive/2026-10-02/results_gm_bconly_s1" "results_gm_bconly_s1"
mkdir -p "$(dirname "results_gm_bconly_s2")"; git mv "_archive/2026-10-02/results_gm_bconly_s2" "results_gm_bconly_s2"
mkdir -p "$(dirname "results_sgate_static")"; git mv "_archive/2026-10-02/results_sgate_static" "results_sgate_static"
mkdir -p "$(dirname "results_sgate_unit")"; git mv "_archive/2026-10-02/results_sgate_unit" "results_sgate_unit"
mkdir -p "$(dirname "results_tgate")"; git mv "_archive/2026-10-02/results_tgate" "results_tgate"
mkdir -p "$(dirname "results_tgate_dec")"; git mv "_archive/2026-10-02/results_tgate_dec" "results_tgate_dec"
mkdir -p "$(dirname "results_tgate_floor")"; git mv "_archive/2026-10-02/results_tgate_floor" "results_tgate_floor"
mkdir -p "$(dirname "results_tgate_fs4")"; git mv "_archive/2026-10-02/results_tgate_fs4" "results_tgate_fs4"
mkdir -p "$(dirname "results_tgate_it400")"; git mv "_archive/2026-10-02/results_tgate_it400" "results_tgate_it400"
mkdir -p "$(dirname "results_tgate_k20")"; git mv "_archive/2026-10-02/results_tgate_k20" "results_tgate_k20"
mkdir -p "$(dirname "results_tgate_k20_fs4")"; git mv "_archive/2026-10-02/results_tgate_k20_fs4" "results_tgate_k20_fs4"
mkdir -p "$(dirname "results_tgate_k20_s1")"; git mv "_archive/2026-10-02/results_tgate_k20_s1" "results_tgate_k20_s1"
mkdir -p "$(dirname "results_tgate_k20_s2")"; git mv "_archive/2026-10-02/results_tgate_k20_s2" "results_tgate_k20_s2"
mkdir -p "$(dirname "results_v11")"; git mv "_archive/2026-10-02/results_v11" "results_v11"
mkdir -p "$(dirname "results_v12")"; git mv "_archive/2026-10-02/results_v12" "results_v12"
mkdir -p "$(dirname "results_v15")"; git mv "_archive/2026-10-02/results_v15" "results_v15"
mkdir -p "$(dirname "results_v16")"; git mv "_archive/2026-10-02/results_v16" "results_v16"
mkdir -p "$(dirname "results_v4")"; git mv "_archive/2026-10-02/results_v4" "results_v4"
mkdir -p "$(dirname "results_v6")"; git mv "_archive/2026-10-02/results_v6" "results_v6"
mkdir -p "$(dirname "results_v7")"; git mv "_archive/2026-10-02/results_v7" "results_v7"
mkdir -p "$(dirname "results_v8")"; git mv "_archive/2026-10-02/results_v8" "results_v8"
mkdir -p "$(dirname "results_wa")"; git mv "_archive/2026-10-02/results_wa" "results_wa"
mkdir -p "$(dirname "results_wa_exact")"; git mv "_archive/2026-10-02/results_wa_exact" "results_wa_exact"
mkdir -p "$(dirname "results_world")"; git mv "_archive/2026-10-02/results_world" "results_world"
mkdir -p "$(dirname "results_ww")"; git mv "_archive/2026-10-02/results_ww" "results_ww"
mkdir -p "$(dirname "results_ablation_A1050.log")"; mv "_archive/2026-10-02/results_ablation_A1050.log" "results_ablation_A1050.log"
mkdir -p "$(dirname "results_ablation_Aall.log")"; mv "_archive/2026-10-02/results_ablation_Aall.log" "results_ablation_Aall.log"
mkdir -p "$(dirname "results_ablation_Aall_s12.log")"; mv "_archive/2026-10-02/results_ablation_Aall_s12.log" "results_ablation_Aall_s12.log"
mkdir -p "$(dirname "results_ablation_B.log")"; mv "_archive/2026-10-02/results_ablation_B.log" "results_ablation_B.log"
mkdir -p "$(dirname "results_figures_export.log")"; mv "_archive/2026-10-02/results_figures_export.log" "results_figures_export.log"
mkdir -p "$(dirname "results_rho_run.log")"; mv "_archive/2026-10-02/results_rho_run.log" "results_rho_run.log"
mkdir -p "$(dirname "results_p1/_rolling_resetbug")"; mv "_archive/2026-10-02/results_p1/_rolling_resetbug" "results_p1/_rolling_resetbug"
mkdir -p "$(dirname "results_field_sens/amp_high.log")"; mv "_archive/2026-10-02/results_field_sens/amp_high.log" "results_field_sens/amp_high.log"
mkdir -p "$(dirname "results_field_sens/amp_low.log")"; mv "_archive/2026-10-02/results_field_sens/amp_low.log" "results_field_sens/amp_low.log"
mkdir -p "$(dirname "results_field_sens/onset_early.log")"; mv "_archive/2026-10-02/results_field_sens/onset_early.log" "results_field_sens/onset_early.log"
mkdir -p "$(dirname "results_field_sens/onset_late.log")"; mv "_archive/2026-10-02/results_field_sens/onset_late.log" "results_field_sens/onset_late.log"
mkdir -p "$(dirname "results_field_sens/win_broad.log")"; mv "_archive/2026-10-02/results_field_sens/win_broad.log" "results_field_sens/win_broad.log"
mkdir -p "$(dirname "results_field_sens/win_narrow.log")"; mv "_archive/2026-10-02/results_field_sens/win_narrow.log" "results_field_sens/win_narrow.log"
mkdir -p "$(dirname "_view_001_acc_scores.png")"; git mv "_archive/2026-10-02/_view_001_acc_scores.png" "_view_001_acc_scores.png"
mkdir -p "$(dirname "_view_001_growth_no_timing_effect.png")"; git mv "_archive/2026-10-02/_view_001_growth_no_timing_effect.png" "_view_001_growth_no_timing_effect.png"
mkdir -p "$(dirname "_view_001_v18_three_gates.png")"; git mv "_archive/2026-10-02/_view_001_v18_three_gates.png" "_view_001_v18_three_gates.png"
mkdir -p "$(dirname "_view_002_deferral_payoff.png")"; git mv "_archive/2026-10-02/_view_002_deferral_payoff.png" "_view_002_deferral_payoff.png"
mkdir -p "$(dirname "deferral_payoff.png")"; git mv "_archive/2026-10-02/deferral_payoff.png" "deferral_payoff.png"
mkdir -p "$(dirname "v18_three_gates.png")"; git mv "_archive/2026-10-02/v18_three_gates.png" "v18_three_gates.png"
mkdir -p "$(dirname "figs")"; git mv "_archive/2026-10-02/figs" "figs"
mkdir -p "$(dirname "figures")"; git mv "_archive/2026-10-02/figures" "figures"
mkdir -p "$(dirname "logs")"; mv "_archive/2026-10-02/logs" "logs"
mkdir -p "$(dirname "notebooks")"; mv "_archive/2026-10-02/notebooks" "notebooks"
mkdir -p "$(dirname "启动实验_v12.sh")"; git mv "_archive/2026-10-02/启动实验_v12.sh" "启动实验_v12.sh"
mkdir -p "$(dirname "启动实验_v13.sh")"; git mv "_archive/2026-10-02/启动实验_v13.sh" "启动实验_v13.sh"
mkdir -p "$(dirname "启动实验_v14.sh")"; git mv "_archive/2026-10-02/启动实验_v14.sh" "启动实验_v14.sh"
mkdir -p "$(dirname "启动实验_v15.sh")"; git mv "_archive/2026-10-02/启动实验_v15.sh" "启动实验_v15.sh"
mkdir -p "$(dirname "启动实验_v16.sh")"; git mv "_archive/2026-10-02/启动实验_v16.sh" "启动实验_v16.sh"
mkdir -p "$(dirname "启动实验_v17.sh")"; git mv "_archive/2026-10-02/启动实验_v17.sh" "启动实验_v17.sh"
mkdir -p "$(dirname "启动实验_v20服务器.sh")"; git mv "_archive/2026-10-02/启动实验_v20服务器.sh" "启动实验_v20服务器.sh"
mkdir -p "$(dirname "scripts/audit_dynamics.py")"; git mv "_archive/2026-10-02/scripts/audit_dynamics.py" "scripts/audit_dynamics.py"
mkdir -p "$(dirname "scripts/baselines.py")"; git mv "_archive/2026-10-02/scripts/baselines.py" "scripts/baselines.py"
mkdir -p "$(dirname "scripts/bench_cpu_vs_gpu.py")"; git mv "_archive/2026-10-02/scripts/bench_cpu_vs_gpu.py" "scripts/bench_cpu_vs_gpu.py"
mkdir -p "$(dirname "scripts/check_historical_data.py")"; git mv "_archive/2026-10-02/scripts/check_historical_data.py" "scripts/check_historical_data.py"
mkdir -p "$(dirname "scripts/diag_horizon.py")"; git mv "_archive/2026-10-02/scripts/diag_horizon.py" "scripts/diag_horizon.py"
mkdir -p "$(dirname "scripts/eval_metrics.py")"; git mv "_archive/2026-10-02/scripts/eval_metrics.py" "scripts/eval_metrics.py"
mkdir -p "$(dirname "scripts/exp_bc_ppo.py")"; git mv "_archive/2026-10-02/scripts/exp_bc_ppo.py" "scripts/exp_bc_ppo.py"
mkdir -p "$(dirname "scripts/exp_counterfactual.py")"; git mv "_archive/2026-10-02/scripts/exp_counterfactual.py" "scripts/exp_counterfactual.py"
mkdir -p "$(dirname "scripts/exp_counterfactual_credit.py")"; git mv "_archive/2026-10-02/scripts/exp_counterfactual_credit.py" "scripts/exp_counterfactual_credit.py"
mkdir -p "$(dirname "scripts/exp_external_temporal.py")"; git mv "_archive/2026-10-02/scripts/exp_external_temporal.py" "scripts/exp_external_temporal.py"
mkdir -p "$(dirname "scripts/exp_opt_quality.py")"; git mv "_archive/2026-10-02/scripts/exp_opt_quality.py" "scripts/exp_opt_quality.py"
mkdir -p "$(dirname "scripts/exp_planning_shock.py")"; git mv "_archive/2026-10-02/scripts/exp_planning_shock.py" "scripts/exp_planning_shock.py"
mkdir -p "$(dirname "scripts/exp_srv_mechanism.py")"; git mv "_archive/2026-10-02/scripts/exp_srv_mechanism.py" "scripts/exp_srv_mechanism.py"
mkdir -p "$(dirname "scripts/exp_srv_scenarios.py")"; git mv "_archive/2026-10-02/scripts/exp_srv_scenarios.py" "scripts/exp_srv_scenarios.py"
mkdir -p "$(dirname "scripts/exp_timing_gate.py")"; git mv "_archive/2026-10-02/scripts/exp_timing_gate.py" "scripts/exp_timing_gate.py"
mkdir -p "$(dirname "scripts/exp_waiting_advantage.py")"; git mv "_archive/2026-10-02/scripts/exp_waiting_advantage.py" "scripts/exp_waiting_advantage.py"
mkdir -p "$(dirname "scripts/verify_budget_identity.py")"; git mv "_archive/2026-10-02/scripts/verify_budget_identity.py" "scripts/verify_budget_identity.py"
mkdir -p "$(dirname "scripts/verify_opportunity_neutral.py")"; git mv "_archive/2026-10-02/scripts/verify_opportunity_neutral.py" "scripts/verify_opportunity_neutral.py"
mkdir -p "$(dirname "scripts/run_batch_v4.sh")"; git mv "_archive/2026-10-02/scripts/run_batch_v4.sh" "scripts/run_batch_v4.sh"
mkdir -p "$(dirname "scripts/run_batch_v6.sh")"; git mv "_archive/2026-10-02/scripts/run_batch_v6.sh" "scripts/run_batch_v6.sh"
mkdir -p "$(dirname "scripts/run_batch_v11.sh")"; git mv "_archive/2026-10-02/scripts/run_batch_v11.sh" "scripts/run_batch_v11.sh"
mkdir -p "$(dirname "scripts/pick_gpu.sh")"; git mv "_archive/2026-10-02/scripts/pick_gpu.sh" "scripts/pick_gpu.sh"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v4")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v4" "data/processed/gm_dataset_v1/exp_v4"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v6")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v6" "data/processed/gm_dataset_v1/exp_v6"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v7")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v7" "data/processed/gm_dataset_v1/exp_v7"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v8")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v8" "data/processed/gm_dataset_v1/exp_v8"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v11")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v11" "data/processed/gm_dataset_v1/exp_v11"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v12")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v12" "data/processed/gm_dataset_v1/exp_v12"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v15")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v15" "data/processed/gm_dataset_v1/exp_v15"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v16")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v16" "data/processed/gm_dataset_v1/exp_v16"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_v17")"; mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_v17" "data/processed/gm_dataset_v1/exp_v17"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_opt_v1")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_opt_v1" "data/processed/gm_dataset_v1/exp_opt_v1"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/exp_smoke")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/exp_smoke" "data/processed/gm_dataset_v1/exp_smoke"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_budget_B2400")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_budget_B2400" "data/processed/gm_dataset_v1/rl_budget_B2400"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_budget_B500")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_budget_B500" "data/processed/gm_dataset_v1/rl_budget_B500"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_budget_B900")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_budget_B900" "data/processed/gm_dataset_v1/rl_budget_B900"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_growth_G0.05")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_growth_G0.05" "data/processed/gm_dataset_v1/rl_growth_G0.05"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_growth_G0.10")"; mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_growth_G0.10" "data/processed/gm_dataset_v1/rl_growth_G0.10"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/rl_v0_sel")"; mv "_archive/2026-10-02/data/processed/gm_dataset_v1/rl_v0_sel" "data/processed/gm_dataset_v1/rl_v0_sel"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/baselines_v15")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/baselines_v15" "data/processed/gm_dataset_v1/baselines_v15"
mkdir -p "$(dirname "data/processed/gm_dataset_v1/eval_v15")"; git mv "_archive/2026-10-02/data/processed/gm_dataset_v1/eval_v15" "data/processed/gm_dataset_v1/eval_v15"
mkdir -p "$(dirname "docs/honest_assessment_v0.md")"; git mv "_archive/2026-10-02/docs/honest_assessment_v0.md" "docs/honest_assessment_v0.md"
mkdir -p "$(dirname "docs/honest_assessment_v1.md")"; git mv "_archive/2026-10-02/docs/honest_assessment_v1.md" "docs/honest_assessment_v1.md"
mkdir -p "$(dirname "docs/honest_assessment_v2.md")"; git mv "_archive/2026-10-02/docs/honest_assessment_v2.md" "docs/honest_assessment_v2.md"
mkdir -p "$(dirname "docs/honest_assessment_v3.md")"; git mv "_archive/2026-10-02/docs/honest_assessment_v3.md" "docs/honest_assessment_v3.md"
mkdir -p "$(dirname "docs/rerun_v2.md")"; git mv "_archive/2026-10-02/docs/rerun_v2.md" "docs/rerun_v2.md"
mkdir -p "$(dirname "docs/reward_defect_v1.md")"; git mv "_archive/2026-10-02/docs/reward_defect_v1.md" "docs/reward_defect_v1.md"
mkdir -p "$(dirname "docs/v15环境改造_实施记录.md")"; git mv "_archive/2026-10-02/docs/v15环境改造_实施记录.md" "docs/v15环境改造_实施记录.md"
mkdir -p "$(dirname "docs/v16改动_实施记录.md")"; git mv "_archive/2026-10-02/docs/v16改动_实施记录.md" "docs/v16改动_实施记录.md"
mkdir -p "$(dirname "docs/v17改动_实施记录.md")"; git mv "_archive/2026-10-02/docs/v17改动_实施记录.md" "docs/v17改动_实施记录.md"
mkdir -p "$(dirname "docs/v18三道门槛_本地结论.md")"; git mv "_archive/2026-10-02/docs/v18三道门槛_本地结论.md" "docs/v18三道门槛_本地结论.md"
mkdir -p "$(dirname "docs/v19_收口_BC微调窗口测试.md")"; git mv "_archive/2026-10-02/docs/v19_收口_BC微调窗口测试.md" "docs/v19_收口_BC微调窗口测试.md"
mkdir -p "$(dirname "docs/v19简化框架_本地结论.md")"; git mv "_archive/2026-10-02/docs/v19简化框架_本地结论.md" "docs/v19简化框架_本地结论.md"
mkdir -p "$(dirname "docs/v20服务器实验_说明.md")"; git mv "_archive/2026-10-02/docs/v20服务器实验_说明.md" "docs/v20服务器实验_说明.md"
mkdir -p "$(dirname "docs/大白话_v15实验与故事线.md")"; git mv "_archive/2026-10-02/docs/大白话_v15实验与故事线.md" "docs/大白话_v15实验与故事线.md"
mkdir -p "$(dirname "docs/大白话_v16实验与故事线.md")"; git mv "_archive/2026-10-02/docs/大白话_v16实验与故事线.md" "docs/大白话_v16实验与故事线.md"
mkdir -p "$(dirname "docs/大白话_v17实验与故事线.md")"; git mv "_archive/2026-10-02/docs/大白话_v17实验与故事线.md" "docs/大白话_v17实验与故事线.md"
mkdir -p "$(dirname "docs/基线与上界_v15.md")"; git mv "_archive/2026-10-02/docs/基线与上界_v15.md" "docs/基线与上界_v15.md"
mkdir -p "$(dirname "docs/实施类指标_v15.md")"; git mv "_archive/2026-10-02/docs/实施类指标_v15.md" "docs/实施类指标_v15.md"
mkdir -p "$(dirname "docs/建议条目审计与改动清单_v15.md")"; git mv "_archive/2026-10-02/docs/建议条目审计与改动清单_v15.md" "docs/建议条目审计与改动清单_v15.md"
mkdir -p "$(dirname "docs/建议条目对照审计_v15.csv")"; git mv "_archive/2026-10-02/docs/建议条目对照审计_v15.csv" "docs/建议条目对照审计_v15.csv"
mkdir -p "$(dirname "docs/批次v4_查验_v5.md")"; git mv "_archive/2026-10-02/docs/批次v4_查验_v5.md" "docs/批次v4_查验_v5.md"
mkdir -p "$(dirname "docs/服务器批次_v4.md")"; git mv "_archive/2026-10-02/docs/服务器批次_v4.md" "docs/服务器批次_v4.md"
mkdir -p "$(dirname "docs/服务器批次_v6.md")"; git mv "_archive/2026-10-02/docs/服务器批次_v6.md" "docs/服务器批次_v6.md"
mkdir -p "$(dirname "docs/服务器批次_v11.md")"; git mv "_archive/2026-10-02/docs/服务器批次_v11.md" "docs/服务器批次_v11.md"
mkdir -p "$(dirname "docs/生态目标诊断_v4.md")"; git mv "_archive/2026-10-02/docs/生态目标诊断_v4.md" "docs/生态目标诊断_v4.md"
mkdir -p "$(dirname "docs/目标对偏好的响应强度_v12数据.csv")"; git mv "_archive/2026-10-02/docs/目标对偏好的响应强度_v12数据.csv" "docs/目标对偏好的响应强度_v12数据.csv"
mkdir -p "$(dirname "docs/修复记录_2026-09-12.md")"; git mv "_archive/2026-10-02/docs/修复记录_2026-09-12.md" "docs/修复记录_2026-09-12.md"
mkdir -p "$(dirname "docs/择时机制_诊断_v1.md")"; git mv "_archive/2026-10-02/docs/择时机制_诊断_v1.md" "docs/择时机制_诊断_v1.md"
mkdir -p "$(dirname "docs/立项与记分分离_实施记录_v1.md")"; git mv "_archive/2026-10-02/docs/立项与记分分离_实施记录_v1.md" "docs/立项与记分分离_实施记录_v1.md"
